# Generated by Django 4.2.2 on 2023-06-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=254, null=True)),
                ('correctanswer', models.CharField(max_length=254, null=True)),
                ('nexttest', models.CharField(max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=254, null=True)),
                ('page', models.CharField(max_length=254, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
            options={
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=254, null=True)),
                ('test', models.CharField(max_length=254, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=2)),
                ('answer', models.CharField(max_length=254, null=True)),
                ('result', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tests',
            },
        ),
    ]
