# Generated by Django 4.2.2 on 2023-06-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module002', '0002_rename_pages_pagestwo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagesTwo',
            new_name='Pages',
        ),
    ]
