# Generated by Django 4.2.1 on 2023-05-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=10, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
