# Generated by Django 4.2.1 on 2023-05-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module001', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name_plural': 'Pages'},
        ),
    ]
