# Generated by Django 4.2.1 on 2023-05-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module001', '0002_alter_pages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='page',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
