# Generated by Django 4.2.1 on 2023-05-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module001', '0004_pages_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=254, null=True)),
                ('test', models.CharField(max_length=254, null=True)),
                ('status', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
            options={
                'verbose_name_plural': 'Tests',
            },
        ),
    ]
