# Generated by Django 4.2.1 on 2023-05-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module001', '0007_alter_tests_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='answer',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
