# Generated by Django 4.2.1 on 2023-06-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module001', '0009_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='nexttest',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
