# Generated by Django 4.2.1 on 2023-05-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question_text',
        ),
    ]
